"""Apply the mined false-positive sources to PHOENIX's land_mask.

Reads sources.json (the auto-mined + auto-promoted catalog), filters to
categories that should suppress wildfire detections, and writes the list
into the land_mask module + purges any existing internal_fires rows
inside these new masks so the map reflects the cleanup immediately.

Categories suppressed:
  - solar_farm, wind_farm, geothermal_plant
  - refinery, petrochemical_complex, gas_flare_stack
  - power_plant_*, quarry, landfill, cement_kiln
  - glasshouse_complex
  - wastewater_treatment, port_industrial
  - volcano, lava_flow, volcanic_caldera
  - urban (when persistent FP detected — e.g. heat island)

NOT suppressed (these stay as potential real fires):
  - agricultural_field, forest, water (no FP risk anyway)
"""
import json
import math
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path("/home/mark/phoenix_false_positives")
SOURCES_JSON = ROOT / "sources.json"
LAND_MASK = Path("/home/mark/.openclaw/workspace/eumetsat_wildfire_detection/src/land_mask.py")
DB = "/media/mark/AI_DGX/eumetsat_data/ground_truth.sqlite"

SUPPRESS_CATEGORIES = {
    "solar_farm", "wind_farm", "geothermal_plant", "power_plant_gas",
    "power_plant_coal", "power_plant_geothermal",
    "refinery", "petrochemical_complex", "gas_flare_stack",
    "quarry", "landfill", "cement_kiln", "glasshouse_complex",
    "wastewater_treatment", "port_industrial",
    "volcano", "lava_flow", "volcanic_caldera", "fumarolic_field",
    "active_stratovolcano", "continuously_active_volcano",
    "industrial_landuse", "industrial_works", "industrial_chimney",
    "petrochemical_gas_flares", "refinery_with_flare", "industrial_port",
    "urban",  # urban heat island when persistent FP detected
}


def hav(a1, b1, a2, b2):
    R = 6371.0
    ra, rb = math.radians(a1), math.radians(a2)
    da = math.radians(a2 - a1)
    dl = math.radians(b2 - b1)
    h = math.sin(da/2)**2 + math.cos(ra)*math.cos(rb)*math.sin(dl/2)**2
    return 2*R*math.asin(math.sqrt(h))


def main():
    data = json.loads(SOURCES_JSON.read_text())
    sources = data["sources"]
    suppress = []
    for s in sources:
        cat = s.get("annotation", {}).get("auto_category") or s.get("category") or s.get("subcategory")
        if cat in SUPPRESS_CATEGORIES:
            suppress.append({
                "id": s["id"],
                "name": s.get("name_en", s["id"]),
                "lat": s["lat"], "lon": s["lon"],
                "radius_km": s["radius_km"],
                "category": cat,
            })
    print(f"Total sources in catalog: {len(sources)}")
    print(f"Suppression list (category match): {len(suppress)}")
    for s in suppress:
        print(f"  {s['id']:48s} {s['category']:25s} ({s['lat']:.3f},{s['lon']:.3f}) r={s['radius_km']}")

    # Inject the full suppression list into land_mask.py — replace any
    # existing INDUSTRIAL_SOURCES list with the union of static + mined.
    text = LAND_MASK.read_text()
    block_start = "INDUSTRIAL_SOURCES = ["
    block_end = "]\n\n\ndef is_inside_industrial"
    if block_start not in text or block_end not in text:
        print("\nERROR: anchors for INDUSTRIAL_SOURCES not found in land_mask.py", file=sys.stderr)
        return 1
    new_lines = ["INDUSTRIAL_SOURCES = ["]
    new_lines.append("    # AUTO-MAINTAINED — regenerated by apply_mined_masks.py from")
    new_lines.append("    # /home/mark/phoenix_false_positives/sources.json on " +
                     datetime.now(timezone.utc).isoformat())
    new_lines.append("    # Do not edit by hand; edit sources.json + re-run the apply script.")
    new_lines.append("    # (name, lat, lon, radius_km)")
    for s in sorted(suppress, key=lambda x: (x["category"], x["id"])):
        new_lines.append(f"    ({s['name']!r}, {s['lat']}, {s['lon']}, {s['radius_km']}),")
    new_lines.append("]")
    new_block = "\n".join(new_lines)

    pre = text.split(block_start)[0]
    post = text.split(block_end)[1]
    new_text = pre + new_block + "\n\n\ndef is_inside_industrial" + post
    LAND_MASK.write_text(new_text)
    print(f"\nUpdated {LAND_MASK} with {len(suppress)} masked sources")

    # Purge existing internal_fires rows that now fall inside the suppression masks
    con = sqlite3.connect(DB)
    rows = list(con.execute(
        "SELECT id, lat, lng FROM internal_fires "
        "WHERE ts > datetime('now','-30 days') "
        "AND source IN ('subpixel_v1_alpha','wind_diff') "
        "AND (raw_json IS NULL OR raw_json NOT LIKE '%expired%')"
    ))
    print(f"\nChecking {len(rows)} live internal_fires rows against new masks...")
    to_expire = []
    for rid, lat, lng in rows:
        for s in suppress:
            if hav(s["lat"], s["lon"], lat, lng) <= s["radius_km"]:
                to_expire.append((rid, s["id"]))
                break
    print(f"  {len(to_expire)} rows fall in suppression masks; expiring them...")
    if to_expire:
        for rid, sid in to_expire[:5]:
            print(f"    id={rid} matched mask={sid}")
        ids = [r[0] for r in to_expire]
        BATCH = 500
        for i in range(0, len(ids), BATCH):
            chunk = ids[i:i+BATCH]
            placeholders = ",".join("?" * len(chunk))
            con.execute(
                f"UPDATE internal_fires SET raw_json = json_set(COALESCE(raw_json,'{{}}'), "
                f"'$.status', 'expired', '$.expired_by_mask', 1) "
                f"WHERE id IN ({placeholders})", chunk)
        con.commit()
        print(f"  EXPIRED {len(to_expire)} rows.")
    con.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
